-- setup-users.sql --
-- PostgreSQL setup for i2b2...
-- Run me like this to substitute password variables:
-- psql -X -f setup-users.sql --set PGI2B2ADMINPASS=\'${PGI2B2ADMINPASS}\' --set PGI2B2USERPASS=\'${PGI2B2USERPASS}\'

\connect i2b2

-- CREATE USER IF NOT EXISTS i2b2 WITH PASSWORD :PGI2B2ADMINPASS;
SELECT 'CREATE USER i2b2;'
WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = 'i2b2')\gexec
ALTER USER i2b2 WITH PASSWORD :PGI2B2ADMINPASS;
ALTER USER i2b2 WITH SUPERUSER;

-- CREATE USER IF NOT EXISTS i2b2demodata WITH PASSWORD :PGI2B2USERPASS;
SELECT 'CREATE USER i2b2demodata;'
WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = 'i2b2demodata')\gexec
ALTER USER i2b2demodata WITH PASSWORD :DS_CRC_PASS;
-- CREATE USER IF NOT EXISTS i2b2hive WITH PASSWORD :PGI2B2USERPASS;
SELECT 'CREATE USER i2b2hive;'
WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = 'i2b2hive')\gexec
ALTER USER i2b2hive WITH PASSWORD :DS_HIVE_PASS;
-- CREATE USER IF NOT EXISTS i2b2imdata WITH PASSWORD :PGI2B2USERPASS;
SELECT 'CREATE USER i2b2imdata;'
WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = 'i2b2imdata')\gexec
ALTER USER i2b2imdata WITH PASSWORD :DS_ONT_PASS;
-- CREATE USER IF NOT EXISTS i2b2metadata WITH PASSWORD :PGI2B2USERPASS;
SELECT 'CREATE USER i2b2metadata;'
WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = 'i2b2metadata')\gexec
ALTER USER i2b2metadata WITH PASSWORD :DS_ONT_PASS;
-- CREATE USER IF NOT EXISTS i2b2pm WITH PASSWORD :PGI2B2USERPASS;
SELECT 'CREATE USER i2b2pm;'
WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = 'i2b2pm')\gexec
ALTER USER i2b2pm WITH PASSWORD :DS_PM_PASS;
-- CREATE USER IF NOT EXISTS i2b2workdata WITH PASSWORD :PGI2B2USERPASS;
SELECT 'CREATE USER i2b2workdata;'
WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = 'i2b2workdata')\gexec
ALTER USER i2b2workdata WITH PASSWORD :DS_WD_PASS;

GRANT ALL PRIVILEGES ON DATABASE i2b2 to i2b2;

GRANT ALL PRIVILEGES ON DATABASE i2b2 to i2b2demodata;
GRANT ALL PRIVILEGES ON DATABASE i2b2 to i2b2hive;
GRANT ALL PRIVILEGES ON DATABASE i2b2 to i2b2imdata;
GRANT ALL PRIVILEGES ON DATABASE i2b2 to i2b2metadata;
GRANT ALL PRIVILEGES ON DATABASE i2b2 to i2b2pm;
GRANT ALL PRIVILEGES ON DATABASE i2b2 to i2b2workdata;
