-- RUN as i2b2 admin user as changing multiple schema

INSERT INTO i2b2pm.PM_PROJECT_DATA (PROJECT_ID, PROJECT_NAME, PROJECT_WIKI, PROJECT_PATH, STATUS_CD)
VALUES('Demo', :'i2b2_PROJECT_NAME', 'http://www.i2b2.org', '/Demo', 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
VALUES('Demo', 'AGG_SERVICE_ACCOUNT', 'USER', 'A');
INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
VALUES('Demo', 'AGG_SERVICE_ACCOUNT', 'MANAGER', 'A');
INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
VALUES('Demo', 'AGG_SERVICE_ACCOUNT', 'DATA_OBFSC', 'A');
INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
VALUES('Demo', 'AGG_SERVICE_ACCOUNT', 'DATA_AGG', 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
VALUES('Demo', 'i2b2', 'MANAGER', 'A');
INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
VALUES('Demo', 'i2b2', 'USER', 'A');
INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
VALUES('Demo', 'i2b2', 'DATA_OBFSC', 'A');

-- Done in: workplace_access_demo_insert_data.sql
-- INSERT INTO i2b2workdata.WORKPLACE_ACCESS(C_TABLE_CD, C_TABLE_NAME, C_PROTECTED_ACCESS, C_HLEVEL, C_NAME, C_USER_ID, C_GROUP_ID, C_SHARE_ID, C_INDEX, C_PARENT_INDEX, C_VISUALATTRIBUTES, C_TOOLTIP)
--   VALUES('demo', 'WORKPLACE','N', 0, 'SHARED', 'shared', 'demo', 'Y', 100, NULL, 'CA', 'SHARED');

-- INSERT INTO i2b2workdata.WORKPLACE_ACCESS(C_TABLE_CD, C_TABLE_NAME, C_PROTECTED_ACCESS, C_HLEVEL, C_NAME, C_USER_ID, C_GROUP_ID, C_SHARE_ID, C_INDEX, C_PARENT_INDEX, C_VISUALATTRIBUTES, C_TOOLTIP)
--  VALUES('demo', 'WORKPLACE','N', 0, '@', '@', '@', 'N', 0, NULL, 'CA', '@');
