INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('DEM|AGE:', 'DEM|AGE', 'Age of patient from demographics data');
INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('DEM|DATE:', 'DEM|DATE', 'Patient date of birth from demographics data');
INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('DEM|MARITAL:', 'DEM|MARITAL', 'Marital Status of patient');
INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('DEM|LANGUAGE:', 'DEM|LANGUAGE', 'Primary language spoken by patient');
INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('DEM|RACE:', 'DEM|RACE', 'Race of patient');
INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('DEM|RELIGION:', 'DEM|RELIGION', 'Religion of patient');
INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('DEM|SEX:', 'DEM|SEX', 'Gender of patient');
INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('DEM|VITAL:', 'DEM|VITAL', 'Vital status of patient');
INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('DEM|ZIPCODE:', 'DEM|ZIPCODE', NULL);
INSERT INTO SCHEMES(C_KEY, C_NAME, C_DESCRIPTION)
  VALUES('(null)', 'None', 'No scheme');

INSERT INTO TABLE_ACCESS(C_TABLE_CD, C_TABLE_NAME, C_PROTECTED_ACCESS, C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_DIMTABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, C_ENTRY_DATE, C_CHANGE_DATE, C_STATUS_CD, VALUETYPE_CD)
  VALUES('i2b2_DEMO', 'I2B2', 'N', 1, '\i2b2\Demographics\', 'Demographics', 'N', 'CA', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Demographics\', NULL, 'Demographics', NULL, NULL, NULL, NULL);
