name: Tag accepted i2b2 Docker Images with version (from PR)
## Update the docker image/package tags by finding the commit sha which was built in the branch
## Adapted from: https://github.com/marketplace/actions/docker-registry-tag
## Manually tag the PR which you've accepted - we find the commit id which was last included in that merge and assume its what was built and accepted (it should be!)

on:
  push:
    tags:
      - v[0-9]+.[0-9]+**

env:
  REGISTRY: ghcr.io
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tag_check:
    ## Checks if the version tag is applied to master branch and commit message is from merging a pull request, then set output "tag_packages" as 'true'
    runs-on: ubuntu-latest
    if: $(git branch -r -a --contains "${{ github.sha }}" | grep -v detached | tr -d "*" | tr -s " " | grep "master")))
    outputs:
      tag_package_status: ${{ steps.status.outputs.tag_packages }}
      package_names: ${{ steps.status.outputs.package_names }}
    steps:
      - name: Pre-requisites
        id: status
        if: startsWith(github.event.head_commit.message, 'Merge pull request')
        run: |
          echo ::set-output name=tag_packages::'true'
          echo "Tagging of packages should happen as we are receiving a tag on master branch..."

  tag_packages:
    ## Work out the commit id which has the actual latest code (from the PR history) and use that to identify the packages to tag
    runs-on: ubuntu-latest
    needs: [tag_check]
    if: needs.tag_check.outputs.tag_package_status == 'true'
    steps:
      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=commit_sha::$(git show --format="%P" "${{ github.sha }}" | cut -d" " -f2)
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add git Version tag to proxy Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-proxy'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      - name: Add git Version tag to web Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-web'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      - name: Add git Version tag to wildfly Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-wildfly'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      - name: Add git Version tag to database Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-database'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      - name: Add git Version tag to api Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-api'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
      - name: Add git Version tag to meta Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ env.REGISTRY }}'
          token: "${{ env.token }}"
          repository: '${{ github.repository }}/${{ github.event.repository.name }}-meta'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            v${{ steps.prep.outputs.version }}
            latest
